application: pepo27devf
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: sillaRodante.application

libraries:
- name: webapp2
  version: latest
- name: numpy
  version: latest